[tool.poetry]
name = "dataset"
description = "Module for approximating the attack surface of an executable"
authors = ["OpenCRS"]
version = "0.1.0"

[tool.poetry.dependencies]
click = "^8.1.3"
docker = "^5.0.3"
flake8 = "^5.0.3"
flake8-annotations = "^2.9.1"
pandas= "1.2.3"
pycparser = "^2.21"
pyelftools = "^0.28"
python = "^3.9"
rich = "^12.5.1"
tabulate= "0.8.9"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
pylint = "^2.14.4"

[tool.poetry.scripts]
dataset = "dataset.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
init-hook="import sys; sys.path.append('.')"

[tool.pylint.MESSAGES_CONTROL]
disable="missing-function-docstring, missing-class-docstring"